name: Container build
on:
  push:
  schedule:
    - cron: '24 2 */7 * *'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-x86:
    runs-on: ubuntu-latest
    container: fedora:43
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build in Docker image without GUIs
        id: build-cli
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          target: cli
          push: false
      - name: Build and push Docker image with GUIs
        id: build-gui
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          target: gui
          push: false
  build-and-push-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          # This image is just the build environment; we haven't installed the MagAO-X software yet
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image without GUIs
        id: build-cli
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          target: cli
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cli
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image with GUIs
        id: build-gui
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          target: gui
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:gui
          labels: ${{ steps.meta.outputs.labels }}
      - name: Clean up old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: magao-x-setup
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
  # build-and-push-arm:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Log in to the Container registry
  #       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  #     - name: Build and push ARM Docker image without GUIs
  #       id: build-cli-arm
  #       uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
  #       with:
  #         context: .
  #         file: Dockerfile
  #         target: cli
  #         platforms: linux/arm64
  #         push: ${{ github.ref == 'refs/heads/main' }}
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cli-arm64
  #         labels: ${{ steps.meta.outputs.labels }}
  #     - name: Build and push ARM Docker image with GUIs
  #       id: build-gui-arm
  #       uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
  #       with:
  #         context: .
  #         file: Dockerfile
  #         target: gui
  #         platforms: linux/arm64
  #         push: ${{ github.ref == 'refs/heads/main' }}
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:gui-arm64
  #         labels: ${{ steps.meta.outputs.labels }}
